/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "rbxnylcptyhvwffpyqll"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJieG55bGNwdHlodndmZnB5cWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzY1ODQsImV4cCI6MjA3MjgxMjU4NH0.Iels3TYpQKNKWqQxHhiH_lmnW680s2r840iHdgLxAxA"
